enum EActionTypes {
	PUSH_TO_DO_LIST = 'PUSH_TO_DO_LIST',
	DELETE_TO_DO = 'DELETE_TO_DO',
	EDIT_TO_DO = 'EDIT_TO_DO',
	PICK_TO_DO = 'PICK_TO_DO',
	TIMER_TYPE_CHANGE = 'TIMER_TYPE_CHANGE',
	CHANGE_READ_ONLY = 'CHANGE_READ_ONLY',
	MARK_TIME = 'MARK_TIME',
	RESET_START_TIMER = 'RESET_START_TIMER',
	STATS_UPDATE = 'STATS_UPDATE',
	INIT_TO_DO_LIST = 'INIT_TO_DO_LIST',
	STATS_GET_DAY = 'STATS_GET_DAY',
	STATS_GET_WEEK = 'STATS_GET_WEEK',
    SET_THEMA = 'SET_THEMA',
    GET_THEMA='GET_THEMA'
}

export default EActionTypes;
